name: Tests

on:
  pull_request:
    branches:
      - main

jobs:
  deploy:
    name: Run tests
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: install pnpm
        run: npm i pnpm@latest -g
      - name: setup pnpm config
        run: pnpm config set store-dir $PNPM_CACHE_FOLDER

      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Install playwright
        run: pnpx playwright install

      - name: Typecheck
        run: pnpm typecheck

      - name: Run package tests
        run: pnpm ci:test:unit

      - name: Run integration tests
        run: pnpm ci:test:integration
        env:
          CI: true
